project:
  type: website
  output-dir: _site
  
website:
  title: "Homepage of C.L. Wyatt"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



