project:
  type: website
  output-dir: docs
  
website:
  title: "C.L. Wyatt"
  navbar:
    logo: images/gravatar.png
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: pubs.qmd
        text: Publications
      - href: about.qmd
        text: About
	
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

