---
title: "Publications"
---

[Google Scholar Profile](http://scholar.google.com/citations?user=6r89o3YAAAAJ)

## Older Publications

### Conference Papers

<ul>
<li>Xiaoxing Li , Xiaojing Long, Christopher Wyatt and the Alzheimer's Disease Neuroimaging Initiative, Registration of Images with Topological Change via Riemannian Embedding, ISBI 2011.</li>

<li>Micah Chambers, Christopher Wyatt, An Analysis of Blood-Oxygen-Level-Dependent Signal Parameter Estimation using Particle Filters, ISBI 2011.</li>

<li>X. Long and C. Wyatt, An Automatic Unsupervised Classification of MR Images in   Alzheimer's Disease, 23rd IEEE Conference on Computer Vision and Pattern Recognition. San Francisco, USA. June 13-18, <em>2010</em>.</li>

<li>X. Li and C. Wyatt, Modeling Topological Changes In Deformable Registration, In<em>Proceedings of the 2010 IEEE international conference on Biomedical imaging: from nano to Macro</em> (ISBI'10). IEEE Press, Piscataway, NJ, USA, 360-363.</li>

<li>V. Rajagopalan, C. L. Wyatt, Combining Morphometric Evidence from Multiple Registration Methods using Dempster-Shafer Theory, Proc. SPIE 7623, 76231U (2010), DOI:10.1117/12.844002 2010.</li>

<li>X. Li and C.L. Wyatt, Brain Segmentation   Performance using T1-weighted Images versus T1 Maps Proc. SPIE 7623, 76233R (2010), DOI:10.1117/12.844278.</li>

<li>X. Long and C. Wyatt, Structural template   formation with discovery of subclasses, Proc. SPIE 7623, 76231B (2010), DOI:10.1117/12.843994.</li>

<li>Yuan Shen and Christopher   L. Wyatt,  Open Implementation of Feature Extraction Methods for Computer Aided   Polyp Detection with Principle Component Analysis, MICCAI 2008   Workshop on computational and visualization challenges in virtual   colonoscopy.</li>

<li>B. Koo, M. Jiang, C.L. Wyatt, G. Wang, "Parameter Optimization for a   Grating-Based Phase Contrast X-ray System," 2008 SPIE International   Symposium on Medical Imaging, Proc. of SPIE Vol. 6916  69160C-1.</li>

<li>J.W. Suh, C.L. Wyatt, "Registration Of Prone And Supine Colons In   The Presence Of Topological Changes," 2008 SPIE International   Symposium on Medical Imaging, Proc. of SPIE Vol. 6916   69160C-1-69160C10.  </li>

<li>J. W. Suh and C. L. Wyatt, Deformable Registration of Supine and Prone Colons Using Centerline Analysis, Proceedings of IEEE International Symposium on Biomedical Imaging, April 2007.</li>

<li>C. L. Wyatt and P. J. Laurienti, Nonrigid Registration of Images with Different Topologies using Embedded Maps, Proceedings of IEEE Engineering in Medicine and Biology Conference, August 2006.</li>

<li>J. W. Suh and C. L. Wyatt, Deformable Registration of Prone and Supine Colons for CT Colonography, Proceedings of IEEE Engineering in Medicine and Biology Conference, August 2006.</li>

<li>C. L. Wyatt, N. Ari, and R. A. Kraft, Spherical Navigator Registration Using Harmonic Analysis for Prospective Motion Correction, 2005 International Conference on Information Processing in Medical Imaging, <em>Lecture Notes in Computer Science</em> Vol. 3565, pgs. 737-748, July 2005.</li>

<li>C.L. Wyatt, Y. Ge, D. J. Vining, Segmentation in Virtual Colonoscopy   using a Geometric Deformable Model,   <em>Proc. of SPIE Vol. 5369, Physiology and Function from Multidimensional Images</em>,    eds. A. Amini, A. Manduca, pgs. 268-279, Feb 2004.</li>

<li>C.L. Wyatt and Y. Ge, A Minimum Reliable Scale Selection in 3D Images,   <em>IEEE Intl. Symp. on Biomedical Imaging</em>,   Arlington VA, April 2004.</li>

</ul>

### Journal Articles

<ul>

<li>S. Zaghlool and C. Wyatt, Missing Data Estimation in FMRI Dynamic Causal Modeling, Frontiers in Neuroscience, vol. 8, no. 191, 2014, DOI=10.3389/fnins.2014.00191.
</li>

<li> X. Li, X. Long, P. Laurienti, and C. Wyatt, Registration of images with varying topology using embedded maps, IEEE transactions on medical imaging, vol. 31, no. 3, pp. 749-65, Mar. 2012.</li>

<li>J.W. Suh and C.L.Wyatt, Registration under Topological Change for CT Colonography, IEEE Transactions on Biomedical Engineering, vol. 58, No. 5, pp. 1403-1411, May, 2011.</li>

<li>J. W. Suh and     C. L. Wyatt,  Deformable Registration of Supine and Prone Colons for CT     Colonography , Journal of Computer Assisted Tomography: November/December 2009 - Volume 33 - Issue 6 - pp 902-911 doi: 10.1097/RCT.0b013e3181a7e2c1.</li>

<li>M. Jiang, C. L. Wyatt, G. Wang, X-Ray Phase-Contrast Imaging with Three 2D Gratings, International Journal of Biomedical Imaging, Volume 2008, Article ID 827152, 8 pages.</li>

<li>C. L. Wyatt, Y. Ge, David Vining,  Segmentation in Virtual Colonoscopy Using a Geometric Deformable Model,  <em>Computerized Medical Imaging and Graphics</em>, 30 (1): 17-30 Jan 2006.</li>

<li>C. L. Wyatt, E. Bayram, Y. Ge,  Minimum Reliable Scale Selection in 3D, <em>IEEE Trans. On Pattern Analysis and Machine Intelligence</em>, 28 (3): 481-U1 March 2006.</li>

<li>E. V. Sullivan, H. J. Sable, W. N Strother, D. P. Friedman, A. Davenport, H. Tillman-Smith, R. A. Kraft, C. L. Wyatt, K. T. Szeliga, N. C. Buchheimer, J. B. Daunais, E. Adalsteinsson, A. Pfefferbaum, K. A Grant, Neuroimaging of Rodent and Primate Models of Alcoholism: Initial Reports from the Integrative Neuroscience Initiative on Alcoholism, <em>Alcoholism: Clinical and Experimental Research</em> Vol. 29 No. 2 pgs 287-294 Feb 2005</li>

<li>C. L. Wyatt, Y. Ge, D. J. Vining, Automatic Segmentation of the Colon for Virtual Colonoscopy, <em>Computerized Medical Imaging and Graphics</em>, Vol. 24 No. 1 pgs. 1-9, Jan-Feb 2000.</li>

</ul>

### Book Chapters

<ul>
<li>M.T. Freedman, M. Loew, Y.P. Wang, C. L. Wyatt, Y. Wang, Chapter 7 Data Processing and Analysis, Biomedical Information Technology, Academic Press 2007.</li>
</ul>

### Dissertation

<ul>
<li>
Christopher Wyatt, "Improving the Conformal Metric: Geodesic Deformable Models for Medical Image Analysis", <i>Ph.D. Dissertation</i>, Wake Forest University School of Medicine, 2002.
</li>
</ul>


